In [16]:
import jupyter_black
jupyter_black.load()

import pandas as pd

from Levenshtein import ratio

from ccl_science_data.common import load_map, EntC, GenReader, iter_dfs, parse_id, get_arr, oa_root
from tqdm.notebook import tqdm

In [4]:
to_drop = [
    "SOCCER PLAYER",
    "ACTOR",
    "SINGER",
    "ATHLETE",
    "MUSICIAN",
    "FILM DIRECTOR",
    "MILITARY PERSONNEL",
    "BASKETBALL PLAYER",
    "CYCLIST",
    "TENNIS PLAYER",
    "RACING DRIVER",
    "WRESTLER",
    "SKIER",
    "SWIMMER",
    "HOCKEY PLAYER",
    "COACH",
    "CHESS PLAYER",
    "BOXER",
    "SKATER",
    "HANDBALL PLAYER",
]

df = pd.concat(
    _df.loc[~_df["occupation"].isin(to_drop) & ~(_df["deathyear"].astype(float) < 1950), :]
    for _df in pd.read_csv(
        "~/Downloads/person_2020_update.csv.bz2", chunksize=1_000_000
    )
)

/tmp/ipykernel_1517865/2115394758.py:24: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat(

In [5]:
e = EntC.AUTHORS
step = "derive_links5"

In [6]:
sizet = 8
adir = f"{step}/{e}-semantic-ids"
ss = 0
sids = []
ftxt = (oa_root /adir /"targets").read_bytes()
for s in map(int, get_arr(f"{adir}/sizes", sizet)):
    sids.append(ftxt[ss : (ss + s)].decode())
    ss = ss + s
sids = sids[:-1]

In [9]:
pd.read_csv('s3://tmp-borza-public-cyx/oa-to-wiki-authors.csv.gz')

        rl_i                  slug       oa_id
0          5       Michael_Grätzel  5109160404
1    2190932       Geoffrey_Hinton  5108093963
2    2190937       Robert_Weinberg  5012557712
3     372694  George_M._Whitesides  5051537916
4    1806632         Omar_M._Yaghi  5044268160
..       ...                   ...         ...
111      965    Roderick_MacKinnon  5025045433
112  2738304      Hilary_Koprowski  5050328478
113      812         Arieh_Warshel  5088665303
114  1391639   Robert_H._MacArthur  5082781942
115  2737520        Demis_Hassabis  5005349213

[116 rows x 3 columns]

In [11]:
ent = EntC.AUTHORS

In [12]:
wdf = pd.concat(_df.dropna() for _df in tqdm(iter_dfs(ent, "ids", cols=["openalex", "wikipedia"])))

0it [00:00, ?it/s]

/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):
/home/borza/science-data/ccl_science_data/common.py:181: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  for _df in pd.read_csv(get_csv_path(ent, sub), chunksize=chunk, usecols=cols):

In [13]:
emap = load_map(ent)

In [14]:
print("".join(map(lambda s: f"- {s}\n", wdf["wikipedia"].tolist())))

- http://en.wikipedia.org/wiki/Josiah_Carberry
- https://es.wikipedia.org/wiki/Mauricio_Toro_Berm%C3%BAdez
- https://en.wikipedia.org/wiki/Christopher_Cs%C3%ADkszentmih%C3%A1lyi
- https://en.wikipedia.org/wiki/Alan_Pilkington
- https://en.wikipedia.org/wiki/Brigitte_Servatius
- https://de.wikipedia.org/wiki/Sebastian_Kempgen
- https://en.wikipedia.org/wiki/Monika_Ritsch-Marte
- https://eu.wikipedia.org/wiki/Iker_Gonz%C3%A1lez-Allende
- https://en.wikipedia.org/wiki/Ihor_Yukhnovskyi

In [17]:
gr = GenReader("..")

In [19]:
adf = (
    pd.DataFrame(
        {
            "name": gr.get_names(EntC.AUTHORS),
            "cc": gr.get_ccounts(EntC.AUTHORS)[:-1],
            "sid": sids,
        }
    )
    .loc[lambda df: df["cc"] > 40_000]
    .sort_values("cc", ascending=False)
    .assign(rl_url=lambda df: "https://www.rankless.org/authors/" + df["sid"])
)

In [20]:
fzdf = pd.concat(
    df.loc[lambda df: df["name"].apply(lambda e: ratio(e, r["name"]) > 0.9)].assign(
        rl_i=i
    )
    for i, r in tqdm(adf.drop_duplicates("name").iterrows())
)

0it [00:00, ?it/s]

In [21]:
o_fdf = (
    fzdf.loc[
        :,
        [
            "id",
            "wd_id",
            "wp_id",
            "slug",
            "name",
            "occupation",
            "birthyear",
            "deathyear",
            "rl_i",
        ],
    ]
    .merge(adf, left_on="rl_i", right_index=True)
    .assign(wiki_url=lambda df: "https://en.wikipedia.org/wiki/" + df["slug"])
)

In [22]:
print(
    "".join(
        f"{e1} -  {e2} ({e3})\n"
        for (e1, e2, e3) in o_fdf.sort_values("occupation")
        .loc[:, ["wiki_url", "rl_url", "occupation"]]
        .values
    )
)

https://en.wikipedia.org/wiki/David_H._Levy -  https://www.rankless.org/authors/david-e-levy (ASTRONOMER)
https://en.wikipedia.org/wiki/Michael_E._Brown -  https://www.rankless.org/authors/michael-s-brown (ASTRONOMER)
https://en.wikipedia.org/wiki/Elizabeth_Blackburn -  https://www.rankless.org/authors/elizabeth-h-blackburn (BIOLOGIST)
https://en.wikipedia.org/wiki/Judah_Folkman -  https://www.rankless.org/authors/judah-folkman (BIOLOGIST)
https://en.wikipedia.org/wiki/Bert_Sakmann -  https://www.rankless.org/authors/bert-sakmann (BIOLOGIST)
https://en.wikipedia.org/wiki/Oliver_Smithies -  https://www.rankless.org/authors/oliver-smithies (BIOLOGIST)
https://en.wikipedia.org/wiki/Erwin_Neher -  https://www.rankless.org/authors/erwin-neher (BIOLOGIST)
https://en.wikipedia.org/wiki/Robert_Sapolsky -  https://www.rankless.org/authors/robert-m-sapolsky (BIOLOGIST)
https://en.wikipedia.org/wiki/Gerald_Edelman -  https://www.rankless.org/authors/gerald-m-edelman (BIOLOGIST)
https://en.wikipedia.org/wiki/Ralph_M._Steinman -  https://www.rankless.org/authors/ralph-m-steinman (BIOLOGIST)
https://en.wikipedia.org/wiki/Francis_Collins -  https://www.rankless.org/authors/francis-s-collins (BIOLOGIST)
https://en.wikipedia.org/wiki/Tomas_Lindahl -  https://www.rankless.org/authors/tomas-lindahl (BIOLOGIST)
https://en.wikipedia.org/wiki/Aaron_Ciechanover -  https://www.rankless.org/authors/aaron-ciechanover (BIOLOGIST)
https://en.wikipedia.org/wiki/Sydney_Brenner -  https://www.rankless.org/authors/sydney-brenner (BIOLOGIST)
https://en.wikipedia.org/wiki/Bruce_Beutler -  https://www.rankless.org/authors/bruce-beutler (BIOLOGIST)
https://en.wikipedia.org/wiki/Jack_W._Szostak -  https://www.rankless.org/authors/jack-w-szostak (BIOLOGIST)
https://en.wikipedia.org/wiki/Stanislas_Dehaene -  https://www.rankless.org/authors/stanislas-dehaene (BIOLOGIST)
https://en.wikipedia.org/wiki/Susumu_Tonegawa -  https://www.rankless.org/authors/susumu-tonegawa (BIOLOGIST)
https://en.wikipedia.org/wiki/Yoshinori_Ohsumi -  https://www.rankless.org/authors/yoshinori-ohsumi (BIOLOGIST)
https://en.wikipedia.org/wiki/James_P._Allison -  https://www.rankless.org/authors/james-p-allison (BIOLOGIST)
https://en.wikipedia.org/wiki/Robert_Weinberg -  https://www.rankless.org/authors/robert-a-weinberg (BIOLOGIST)
https://en.wikipedia.org/wiki/Rolf_Singer -  https://www.rankless.org/authors/wolf-singer (BIOLOGIST)
https://en.wikipedia.org/wiki/Svante_Pääbo -  https://www.rankless.org/authors/svante-paabo (BIOLOGIST)
https://en.wikipedia.org/wiki/Paul_Greengard -  https://www.rankless.org/authors/paul-greengard (BIOLOGIST)
https://en.wikipedia.org/wiki/Robert_H._MacArthur -  https://www.rankless.org/authors/robert-h-macarthur (BIOLOGIST)
https://en.wikipedia.org/wiki/Christian_Drosten -  https://www.rankless.org/authors/christian-drosten (BIOLOGIST)
https://en.wikipedia.org/wiki/David_Baltimore -  https://www.rankless.org/authors/david-baltimore (BIOLOGIST)
https://en.wikipedia.org/wiki/W._D._Hamilton -  https://www.rankless.org/authors/w-d-hamilton-2 (BIOLOGIST)
https://en.wikipedia.org/wiki/J._Michael_Bishop -  https://www.rankless.org/authors/j-michael-bishop (BIOLOGIST)
https://en.wikipedia.org/wiki/H._Robert_Horvitz -  https://www.rankless.org/authors/h-robert-horvitz (BIOLOGIST)
https://en.wikipedia.org/wiki/Paul_Nurse -  https://www.rankless.org/authors/paul-nurse (BIOLOGIST)
https://en.wikipedia.org/wiki/Günter_Blobel -  https://www.rankless.org/authors/gunter-blobel (BIOLOGIST)
https://en.wikipedia.org/wiki/David_Richards_(motorsport) -  https://www.rankless.org/authors/david-richardson (BUSINESSPERSON)
https://en.wikipedia.org/wiki/Alan_MacDiarmid -  https://www.rankless.org/authors/alan-g-macdiarmid (CHEMIST)
https://en.wikipedia.org/wiki/Robert_Huber -  https://www.rankless.org/authors/robert-huber (CHEMIST)
https://en.wikipedia.org/wiki/Michael_Grätzel -  https://www.rankless.org/authors/michael-graetzel (CHEMIST)
https://en.wikipedia.org/wiki/Richard_R._Ernst -  https://www.rankless.org/authors/richard-r-ernst (CHEMIST)
https://en.wikipedia.org/wiki/Roald_Hoffmann -  https://www.rankless.org/authors/roald-hoffmann (CHEMIST)
https://en.wikipedia.org/wiki/Frances_Arnold -  https://www.rankless.org/authors/frances-h-arnold (CHEMIST)
https://en.wikipedia.org/wiki/Paul_J._Crutzen -  https://www.rankless.org/authors/paul-j-crutzen (CHEMIST)
https://en.wikipedia.org/wiki/Richard_R._Schrock -  https://www.rankless.org/authors/richard-r-schrock (CHEMIST)
https://en.wikipedia.org/wiki/Harry_B._Gray -  https://www.rankless.org/authors/harry-b-gray (CHEMIST)
https://en.wikipedia.org/wiki/Ryōji_Noyori -  https://www.rankless.org/authors/ryoji-noyori (CHEMIST)
https://en.wikipedia.org/wiki/F._Albert_Cotton -  https://www.rankless.org/authors/f-albert-cotton (CHEMIST)
https://en.wikipedia.org/wiki/Peter_J._Ratcliffe -  https://www.rankless.org/authors/peter-j-ratcliffe (CHEMIST)
https://en.wikipedia.org/wiki/Alfred_G._Gilman -  https://www.rankless.org/authors/alfred-g-gilman (CHEMIST)
https://en.wikipedia.org/wiki/Michael_Grätzel -  https://www.rankless.org/authors/michael-gratzel (CHEMIST)
https://en.wikipedia.org/wiki/Stanley_B._Prusiner -  https://www.rankless.org/authors/stanley-b-prusiner (CHEMIST)
https://en.wikipedia.org/wiki/Frederick_Sanger -  https://www.rankless.org/authors/frederick-sanger (CHEMIST)
https://en.wikipedia.org/wiki/Joseph_L._Goldstein -  https://www.rankless.org/authors/joseph-l-goldstein (CHEMIST)
https://en.wikipedia.org/wiki/Thomas_C._Südhof -  https://www.rankless.org/authors/thomas-c-sudhof (CHEMIST)
https://en.wikipedia.org/wiki/Bengt_I._Samuelsson -  https://www.rankless.org/authors/bengt-samuelsson (CHEMIST)
https://en.wikipedia.org/wiki/Allen_J._Bard -  https://www.rankless.org/authors/allen-j-bard (CHEMIST)
https://en.wikipedia.org/wiki/Roderick_MacKinnon -  https://www.rankless.org/authors/roderick-mackinnon (CHEMIST)
https://en.wikipedia.org/wiki/Kurt_Wüthrich -  https://www.rankless.org/authors/kurt-wuthrich (CHEMIST)
https://en.wikipedia.org/wiki/Roger_Y._Tsien -  https://www.rankless.org/authors/roger-y-tsien (CHEMIST)
https://en.wikipedia.org/wiki/C._N._R._Rao -  https://www.rankless.org/authors/c-n-r-rao (CHEMIST)
https://en.wikipedia.org/wiki/Martin_Karplus -  https://www.rankless.org/authors/martin-karplus (CHEMIST)
https://en.wikipedia.org/wiki/Omar_M._Yaghi -  https://www.rankless.org/authors/omar-m-yaghi (CHEMIST)
https://en.wikipedia.org/wiki/Robert_H._Grubbs -  https://www.rankless.org/authors/robert-h-grubbs (CHEMIST)
https://en.wikipedia.org/wiki/Albert_Hofmann -  https://www.rankless.org/authors/albert-hofman (CHEMIST)
https://en.wikipedia.org/wiki/George_M._Whitesides -  https://www.rankless.org/authors/george-m-whitesides (CHEMIST)
https://en.wikipedia.org/wiki/Krzysztof_Matyjaszewski -  https://www.rankless.org/authors/krzysztof-matyjaszewski (CHEMIST)
https://en.wikipedia.org/wiki/Alan_J._Heeger -  https://www.rankless.org/authors/alan-j-heeger (CHEMIST)
https://en.wikipedia.org/wiki/Jennifer_Doudna -  https://www.rankless.org/authors/jennifer-a-doudna (CHEMIST)
https://en.wikipedia.org/wiki/Arieh_Warshel -  https://www.rankless.org/authors/arieh-warshel (CHEMIST)
https://en.wikipedia.org/wiki/Fraser_Stoddart -  https://www.rankless.org/authors/j-fraser-stoddart (CHEMIST)
https://en.wikipedia.org/wiki/Craig_Thompson -  https://www.rankless.org/authors/craig-b-thompson (COMIC ARTIST)
https://en.wikipedia.org/wiki/Karel_Svoboda_(composer) -  https://www.rankless.org/authors/karel-svoboda (COMPOSER)
https://en.wikipedia.org/wiki/James_Horner -  https://www.rankless.org/authors/james-hone (COMPOSER)
https://en.wikipedia.org/wiki/Demis_Hassabis -  https://www.rankless.org/authors/demis-hassabis (COMPUTER SCIENTIST)
https://en.wikipedia.org/wiki/Lotfi_A._Zadeh -  https://www.rankless.org/authors/lotfi-a-zadeh (COMPUTER SCIENTIST)
https://en.wikipedia.org/wiki/Geoffrey_Hinton -  https://www.rankless.org/authors/geoffrey-e-hinton (COMPUTER SCIENTIST)
https://en.wikipedia.org/wiki/Yann_LeCun -  https://www.rankless.org/authors/yann-lecun (COMPUTER SCIENTIST)
https://en.wikipedia.org/wiki/Michael_Clarke_(cricketer) -  https://www.rankless.org/authors/michael-f-clarke (CRICKETER)
https://en.wikipedia.org/wiki/Michael_Porter -  https://www.rankless.org/authors/michael-e-porter (ECONOMIST)
https://en.wikipedia.org/wiki/Jean_Tirole -  https://www.rankless.org/authors/jean-tirole (ECONOMIST)
https://en.wikipedia.org/wiki/Oliver_E._Williamson -  https://www.rankless.org/authors/oliver-e-williamson (ECONOMIST)
https://en.wikipedia.org/wiki/Richard_Thaler -  https://www.rankless.org/authors/richard-h-thaler (ECONOMIST)
https://en.wikipedia.org/wiki/Joseph_Stiglitz -  https://www.rankless.org/authors/joseph-e-stiglitz (ECONOMIST)
https://en.wikipedia.org/wiki/Robert_F._Engle -  https://www.rankless.org/authors/robert-f-engle (ECONOMIST)
https://en.wikipedia.org/wiki/Herbert_A._Simon -  https://www.rankless.org/authors/herbert-a-simon (ECONOMIST)
https://en.wikipedia.org/wiki/Daron_Acemoglu -  https://www.rankless.org/authors/daron-acemoglu (ECONOMIST)
https://en.wikipedia.org/wiki/Raghuram_Rajan -  https://www.rankless.org/authors/raghuram-g-rajan (ECONOMIST)
https://en.wikipedia.org/wiki/Robert_C._Merton -  https://www.rankless.org/authors/robert-c-merton (ECONOMIST)
https://en.wikipedia.org/wiki/Leon_O._Chua -  https://www.rankless.org/authors/leon-o-chua (ENGINEER)
https://en.wikipedia.org/wiki/Stanley_Williams -  https://www.rankless.org/authors/r-stanley-williams (EXTREMIST)
https://en.wikipedia.org/wiki/Michael_E._Mann -  https://www.rankless.org/authors/michael-p-manns (GEOLOGIST)
https://en.wikipedia.org/wiki/Peter_Brown_(historian) -  https://www.rankless.org/authors/peter-brown (HISTORIAN)
https://en.wikipedia.org/wiki/John_Roberts -  https://www.rankless.org/authors/john-robertson (JUDGE)
https://en.wikipedia.org/wiki/Terence_Tao -  https://www.rankless.org/authors/terence-tao (MATHEMATICIAN)
https://en.wikipedia.org/wiki/Yitang_Zhang -  https://www.rankless.org/authors/yang-zhang (MATHEMATICIAN)
https://en.wikipedia.org/wiki/John_G._Thompson -  https://www.rankless.org/authors/john-f-thompson (MATHEMATICIAN)
https://en.wikipedia.org/wiki/Steven_Strogatz -  https://www.rankless.org/authors/steven-h-strogatz (MATHEMATICIAN)
https://en.wikipedia.org/wiki/Helena_Christensen -  https://www.rankless.org/authors/helen-christensen (MODEL)
https://en.wikipedia.org/wiki/Michel_Foucault -  https://www.rankless.org/authors/michel-foucault (PHILOSOPHER)
https://en.wikipedia.org/wiki/Bruno_Latour -  https://www.rankless.org/authors/bruno-latour (PHILOSOPHER)
https://en.wikipedia.org/wiki/Tasuku_Honjo -  https://www.rankless.org/authors/tasuku-honjo (PHYSICIAN)
https://en.wikipedia.org/wiki/David_H._Hubel -  https://www.rankless.org/authors/david-h-hubel (PHYSICIAN)
https://en.wikipedia.org/wiki/Peter_C._Gøtzsche -  https://www.rankless.org/authors/peter-c-gotzsche (PHYSICIAN)
https://en.wikipedia.org/wiki/Andrew_Schally -  https://www.rankless.org/authors/andrew-v-schally (PHYSICIAN)
https://en.wikipedia.org/wiki/Hilary_Koprowski -  https://www.rankless.org/authors/hilary-koprowski (PHYSICIAN)
https://en.wikipedia.org/wiki/Rolf_M._Zinkernagel -  https://www.rankless.org/authors/rolf-m-zinkernagel (PHYSICIAN)
https://en.wikipedia.org/wiki/Richard_Doll -  https://www.rankless.org/authors/richard-doll (PHYSICIAN)
https://en.wikipedia.org/wiki/Richard_Axel -  https://www.rankless.org/authors/richard-axel (PHYSICIAN)
https://en.wikipedia.org/wiki/Gregg_L._Semenza -  https://www.rankless.org/authors/gregg-l-semenza (PHYSICIAN)
https://en.wikipedia.org/wiki/Robert_Lefkowitz -  https://www.rankless.org/authors/robert-j-lefkowitz (PHYSICIAN)
https://en.wikipedia.org/wiki/George_E._P._Box -  https://www.rankless.org/authors/george-e-p-box (PHYSICIAN)
https://en.wikipedia.org/wiki/Shinya_Yamanaka -  https://www.rankless.org/authors/shinya-yamanaka (PHYSICIAN)
https://en.wikipedia.org/wiki/Michael_Fisher -  https://www.rankless.org/authors/michael-e-fisher (PHYSICIST)
https://en.wikipedia.org/wiki/Cumrun_Vafa -  https://www.rankless.org/authors/cumrun-vafa (PHYSICIST)
https://en.wikipedia.org/wiki/Andrei_Linde -  https://www.rankless.org/authors/andrei-linde (PHYSICIST)
https://en.wikipedia.org/wiki/Shuji_Nakamura -  https://www.rankless.org/authors/shuji-nakamura (PHYSICIST)
https://en.wikipedia.org/wiki/John_B._Goodenough -  https://www.rankless.org/authors/john-b-goodenough (PHYSICIST)
https://en.wikipedia.org/wiki/Albert-László_Barabási -  https://www.rankless.org/authors/albertlaszlo-barabasi (PHYSICIST)
https://en.wikipedia.org/wiki/Anton_Zeilinger -  https://www.rankless.org/authors/anton-zeilinger (PHYSICIST)
https://en.wikipedia.org/wiki/Edward_Witten -  https://www.rankless.org/authors/edward-witten (PHYSICIST)
https://en.wikipedia.org/wiki/Sumio_Iijima -  https://www.rankless.org/authors/sumio-iijima (PHYSICIST)
https://en.wikipedia.org/wiki/Frank_Wilczek -  https://www.rankless.org/authors/frank-wilczek (PHYSICIST)
https://en.wikipedia.org/wiki/Steven_Weinberg -  https://www.rankless.org/authors/steven-weinberg (PHYSICIST)
https://en.wikipedia.org/wiki/Steven_Chu -  https://www.rankless.org/authors/steven-chu (PHYSICIST)
https://en.wikipedia.org/wiki/Jürgen_Kurths -  https://www.rankless.org/authors/jurgen-kurths (PHYSICIST)
https://en.wikipedia.org/wiki/Francis_Fukuyama -  https://www.rankless.org/authors/francis-fukuyama (POLITICAL SCIENTIST)
https://en.wikipedia.org/wiki/Robert_D._Putnam -  https://www.rankless.org/authors/robert-d-putnam (POLITICAL SCIENTIST)
https://en.wikipedia.org/wiki/Chen_Cheng -  https://www.rankless.org/authors/chen-chen-2 (POLITICIAN)
https://en.wikipedia.org/wiki/Robert_H._Jackson -  https://www.rankless.org/authors/robert-b-jackson (POLITICIAN)
https://en.wikipedia.org/wiki/David_Paterson -  https://www.rankless.org/authors/david-l-paterson (POLITICIAN)
https://en.wikipedia.org/wiki/Antonio_Saca -  https://www.rankless.org/authors/antonio-sica (POLITICIAN)
https://en.wikipedia.org/wiki/Garret_FitzGerald -  https://www.rankless.org/authors/garret-a-fitzgerald (POLITICIAN)
https://en.wikipedia.org/wiki/Michael_Hayden_(general) -  https://www.rankless.org/authors/michael-r-hayden (POLITICIAN)
https://en.wikipedia.org/wiki/Brian_Williams -  https://www.rankless.org/authors/bryan-williams (PRESENTER)
https://en.wikipedia.org/wiki/Albert_Bandura -  https://www.rankless.org/authors/albert-bandura (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Giacomo_Rizzolatti -  https://www.rankless.org/authors/giacomo-rizzolatti-2 (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Robert_Sternberg -  https://www.rankless.org/authors/robert-j-sternberg (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Daniel_Kahneman -  https://www.rankless.org/authors/daniel-kahneman (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Amos_Tversky -  https://www.rankless.org/authors/amos-tversky (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Geert_Hofstede -  https://www.rankless.org/authors/geert-hofstede (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Aaron_T._Beck -  https://www.rankless.org/authors/aaron-t-beck (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Simon_Baron-Cohen -  https://www.rankless.org/authors/simon-baroncohen (PSYCHOLOGIST)
https://en.wikipedia.org/wiki/Francesco_Monterisi -  https://www.rankless.org/authors/francesco-montorsi (RELIGIOUS FIGURE)
https://en.wikipedia.org/wiki/Hirotugu_Akaike -  https://www.rankless.org/authors/hirotugu-akaike (RELIGIOUS FIGURE)
https://en.wikipedia.org/wiki/Matthew_Stevens -  https://www.rankless.org/authors/matthew-stephens (SNOOKER)
https://en.wikipedia.org/wiki/Erving_Goffman -  https://www.rankless.org/authors/erving-goffman (SOCIOLOGIST)
https://en.wikipedia.org/wiki/Anthony_Giddens -  https://www.rankless.org/authors/anthony-giddens (SOCIOLOGIST)
https://en.wikipedia.org/wiki/Robert_K._Merton -  https://www.rankless.org/authors/robert-c-merton (SOCIOLOGIST)
https://en.wikipedia.org/wiki/Pierre_Bourdieu -  https://www.rankless.org/authors/pierre-bourdieu (SOCIOLOGIST)
https://en.wikipedia.org/wiki/Erik_Lindh -  https://www.rankless.org/authors/erik-lindahl (TABLE TENNIS PLAYER)
https://en.wikipedia.org/wiki/Michael_Bishop_(author) -  https://www.rankless.org/authors/j-michael-bishop (WRITER)
https://en.wikipedia.org/wiki/John_W._Campbell -  https://www.rankless.org/authors/john-y-campbell (WRITER)
https://en.wikipedia.org/wiki/James_C._Collins -  https://www.rankless.org/authors/james-j-collins (WRITER)
https://en.wikipedia.org/wiki/Anthony_Powell -  https://www.rankless.org/authors/anthony-howell (WRITER)

In [23]:
misses = [
    "https://www.rankless.org/authors/david-e-levy",
    "https://www.rankless.org/authors/michael-s-brown",
    "https://www.rankless.org/authors/wolf-singer",
    "https://www.rankless.org/authors/david-richardson",
    "https://www.rankless.org/authors/albert-hofman",
    "https://www.rankless.org/authors/james-hone",
    "https://www.rankless.org/authors/karel-svoboda",
    "https://www.rankless.org/authors/michael-f-clarke",
    "https://www.rankless.org/authors/r-stanley-williams",
    "https://www.rankless.org/authors/michael-p-manns",
    "https://www.rankless.org/authors/john-robertson",
    "https://www.rankless.org/authors/yang-zhang",
    "https://www.rankless.org/authors/john-f-thompson",
    "https://www.rankless.org/authors/helen-christensen",
    "https://www.rankless.org/authors/robert-b-jackson",
    "https://www.rankless.org/authors/michael-r-hayden",
    "https://www.rankless.org/authors/david-l-paterson",
    "https://www.rankless.org/authors/garret-a-fitzgerald",
    "https://www.rankless.org/authors/chen-chen-2",
    "https://www.rankless.org/authors/bryan-williams",
    "https://www.rankless.org/authors/giacomo-rizzolatti-2",
    "https://www.rankless.org/authors/francesco-montorsi",
    "https://www.rankless.org/authors/matthew-stephens",
    "https://www.rankless.org/authors/erik-lindahl",
    "https://www.rankless.org/authors/anthony-howell",
    "https://www.rankless.org/authors/james-j-collins",
    "https://www.rankless.org/authors/john-y-campbell",
    "https://www.rankless.org/authors/w-d-hamilton-2",  # TODO
    "https://www.rankless.org/authors/craig-b-thompson",
    "https://www.rankless.org/authors/j-michael-bishop",
]

In [117]:
o_fdf.set_index("rl_url").drop(misses).to_csv("~/Downloads/rl-wiki-matches.csv")

In [24]:
match_df = (
    o_fdf.set_index("rl_url")
    .drop(misses)
    .set_index("rl_i")
    .assign(oa_id=pd.Series({v: k for k, v in emap.items()}))
)

In [126]:
match_df.loc[:, ["slug", "oa_id"]].to_csv("~/Downloads/oa-to-wiki-authors.csv.gz")

In [77]:
fzdf["occupation"].value_counts()#["rl_i"].nunique()

occupation
CHEMIST                33
BIOLOGIST              30
PHYSICIST              13
PHYSICIAN              12
ECONOMIST              10
PSYCHOLOGIST            8
POLITICIAN              5
SOCIOLOGIST             4
COMPUTER SCIENTIST      4
WRITER                  4
MATHEMATICIAN           3
POLITICAL SCIENTIST     2
COMPOSER                2
ASTRONOMER              2
RELIGIOUS FIGURE        2
PHILOSOPHER             2
COMIC ARTIST            1
SNOOKER                 1
JUDGE                   1
PRESENTER               1
TABLE TENNIS PLAYER     1
GEOLOGIST               1
BUSINESSPERSON          1
EXTREMIST               1
ENGINEER                1
CRICKETER               1
MODEL                   1
Name: count, dtype: int64

In [57]:
mdf = adf.merge(df)

In [58]:
mdf["occupation"].value_counts()

occupation
CHEMIST                25
BIOLOGIST              23
PHYSICIST              11
PHYSICIAN               9
PSYCHOLOGIST            6
ECONOMIST               5
COMPUTER SCIENTIST      3
SOCIOLOGIST             3
POLITICAL SCIENTIST     2
PHILOSOPHER             2
RELIGIOUS FIGURE        1
ENGINEER                1
COMPOSER                1
Name: count, dtype: int64

In [55]:
mdf.loc[lambda df: df["occupation"].isin(["COMPOSER", "RELIGIOUS FIGURE"])]

               name     cc  ...  coefficient_of_variation        hpi
62  Hirotugu Akaike  47153  ...                  2.701078  59.306662
72    Karel Svoboda  44321  ...                  2.661908  65.074659

[2 rows x 35 columns]